# Generated by Django 4.2 on 2024-09-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
                ('price', models.TextField(null=True, verbose_name='Precio')),
                ('stock', models.TextField(null=True, verbose_name='Stock')),
                ('category', models.TextField(null=True, verbose_name='Categoría')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('date', models.TextField(null=True, verbose_name='Fecha')),
            ],
        ),
    ]
