# Generated by Django 4.2 on 2024-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_product_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='link'),
        ),
    ]
