# Generated by Django 4.2 on 2024-09-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Compra')),
                ('price_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Venta')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='IVA')),
                ('transport', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transporte')),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Ganancia')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product', verbose_name='Producto')),
            ],
        ),
    ]
