# Generated by Django 4.2 on 2024-09-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_marketstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketstudy',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='marketstudy',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='marketstudy',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Venta'),
        ),
    ]
